#!/usr/bin/env bash

# Kill other instances
#for pid in $(ps -ax | grep "scripts/audio" | grep -v "grep" | awk '{print $1}'); do
#	[ "${pid}" -eq "$$" ] || kill -9 ${pid}
#done

while true; do
	# Set microphone volume
	pactl set-source-volume @DEFAULT_SOURCE@ 32%
	
	# Set default source
	pactl set-source-port @DEFAULT_SOURCE@ analog-input-headset-mic
done