#!/usr/bin/env bash

if [[ $(pgrep -f i3) ]]; then 
	# Create a screenshot
	maim > ~/.screenlock.png

	# Blur screenshot
	convert ~/.screenlock.png -filter Gaussian -blur 0x8 ~/.screenlock.png

	# i3lock
	if [[ $(pgrep -f i3) ]]; then i3lock -i ~/.screenlock.png; fi
elif [[ $(pacman -Q swaylock-effects) ]]; then
	swaylock \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
	--ring-color bb00cc \
	--key-hl-color 880033 \
	--line-color 00000000 \
	--inside-color 00000088 \
	--separator-color 00000000 \
	--grace 2 \
	--fade-in 0.2
elif [[ $(pgrep -f sway) ]]; then
	# Create screenshot
	grim  ~/.screenlock.png

	# Blur screenshot
	convert ~/.screenlock.png -filter Gaussian -blur 0x8 ~/.screenlock.png

	# swaylock
	if [[ $(pgrep -f swaylock) ]]; then swaylock -i ~/.screenlock.png; fi

fi
