#!/usr/bin/env bash

echo "######################"
echo "Pacman Snapshot Script"
echo "######################"
echo ""

echo "Operation Mode"
echo "1 - Install"
echo "2 - Remove"
echo "3 - Upgrade System"
echo "4 - Update database"
read MODE
echo ""

# Packages
if [[ ${MODE} -eq "1" ]]; then echo "Enter packages name to install: "
elif [[ ${MODE} -eq "2" ]]; then echo "Enter packages name to remove: "; fi

if [[ ${MODE} -ne "3" && ${MODE} -ne "4" ]]; then read PACKAGES; fi
echo ""

# Correct package names
if [[ ${MODE} -ne "3" && ${MODE} -ne "4" ]]; then PACKAGES_CORRECTED=$(echo ${PACKAGES} | awk 'gsub(" ", "-")'); fi

# Single package (WORKAROUND)
if [[ ${MODE} -ne "3" && ${MODE} -ne "4" ]]; then
	echo "Installing single package?"
	echo "1 - Yes"
	echo "2 - No"
	read SINGLE_PACKAGE
	echo ""
	
	if [[ ${SINGLE_PACKAGE} -eq "1" ]]; then 
		PACKAGES_CORRECTED=${PACKAGES}
		echo "You choose single package"
	fi
fi

# Snapshot name
if [[ ${MODE} -eq "1" ]]; then SNAPSHOT_NAME=$(date +%d_%m_%Y-%H-%M)-install-${PACKAGES_CORRECTED}
elif [[ ${MODE} -eq "2" ]]; then SNAPSHOT_NAME=$(date +%d_%m_%Y-%H-%M)-remove-${PACKAGES_CORRECTED}
elif [[ ${MODE} -eq "3" ]]; then SNAPSHOT_NAME=$(date +%d_%m_%Y-%H-%M)-system-upgrade
else SNAPSHOT_NAME=$(date +%d_%m_%Y-%H-%M)-database-update; fi

# Snapshot path
SNAPSHOT_PATH=/.snapshots

# Snapshot
btrfs subvol snapshot "/" "${SNAPSHOT_PATH}/${SNAPSHOT_NAME}"

# Install
if [[ ${MODE} -eq "1" ]]; then
	pacman -S ${PACKAGES}
# Remove
elif [[ ${MODE} -eq "2" ]]; then
	pacman -R ${PACKAGES}
# Update
elif [[ ${MODE} -eq "3" ]]; then
	pacman -Syu
else 
	pacman -Fy
	pacman -Sy
fi

# Ask to save snapshot
echo "You want to delete snapshot?"
echo "1 - Save (No)"
echo "2 - Delete (Yes)"
read DELETE_SNAPSHOT
echo ""

if [[ ${DELETE_SNAPSHOT} -eq "1" ]]; then
	echo "Snapshot Saved"
	echo ""
	echo "Reloading grub"
	grub-mkconfig -o /boot/grub/grub.cfg
elif [[ ${DELETE_SNAPSHOT} -eq "2" ]]; then
	rm -rf "${SNAPSHOT_PATH}/${SNAPSHOT_NAME}"
	echo "Snapshot deleted"
fi
