#!/bin/bash
# Basic explanation
# disk = Hibernate to disk
# ram = Suspend to ram 
# freeze = Suspend and if necessary hibernate to disk

swap="/dev/sda6"
command="$@"

# Check
[[ ${UID} != "0" ]] && echo "This script need to be run as root"

# Set disk to save
echo "Setting swap partition..."
echo "$swap" > "/sys/power/resume"

# Suspend
case "$command" in
	*"hib"*)
			echo "Hibernating..."
			resume="$swap" echo "disk" >> "/sys/power/state"
	;;
	*"sus"*)
			echo "Suspending..."
			resume="$swap" echo "ram" > "/sys/power/state"
	;;
	*"hyb"*)
			echo "Suspending(hybrid).."
			resume="$swap" echo "freeze" > "/sys/power/state"
	;;
esac
