#!/usr/bin/env bash
YT=yt-dlp

echo "Video/Song link: "
read LINK
echo ""

echo "1 - Audio only"
echo "2 - Video"
read DOWNLOAD
echo ""

echo "Category:"
read CATEGORY

if [[ ${DOWNLOAD} -eq "1" ]]; then
	${YT} -x --audio-format wav --audio-quality 0 --yes-playlist ${LINK} --restrict-filenames -o "~/musics/${CATEGORY}/%(playlist)s/%(title)s.%(ext)s"
fi
